### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by git-mosis** [tomoncle/mxnet-spring-samples#1]
Bringing over the issue thread from https://github.com/apache/incubator-mxnet/issues/14943 ...

Thanks @tomoncle, so I should not be hitting the `/files` endpoint but when uploading a new photo, instead I should hit `/files/detectImage` to upload the photo and detect it. 

When I tried `/files/detectImage`, to upload an image I get the error below:

```
{"path":"/files/detectImage","data":null,"method":"POST","message":"Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.mxnet.Symbol$","status":500,"timestamp":"2019-05-29T01:44:03.037+0000"}
```

From `14943`, you mentioned that it'd be good to update maven. Thanks for the hint. I see you have the linux mxnet dependency. When I updated it the `mxnet-spring-samples/mxnet-spring-samples-image-recognition/pom.xml` file with the below: 

```
        <dependency>
            <groupId>org.apache.mxnet</groupId>
            <artifactId>mxnet-full_2.11-osx-x86_64-cpu</artifactId>
            <version>1.4.0</version>
        </dependency>
```

From there, it still isn't working and get objects that cannot be resolved, like 
`import org.apache.mxnet.javaapi.Image;`. Then I noticed in the `mxnet-spring-samples/pom.xml` file on line 82, there is: 

```
<mxnet-cpu.version>[1.5.0-SNAPSHOT, )</mxnet-cpu.version>
```

Can you verify the MXnet cpu version the project is using?

**Comment by tomoncle** [comment]
I used the snapshot version, and I had a problem with the Image object before. The author told me this is a new feature in the 1.5 snapshot version, so I used "[1.5.0-SNAPSHOT,)".
The version is "mxnet-full_2.11-linux-x86_64-cpu-1.5.0-20190504.203714-141.jar".

If you want to get Mac OS files, you need to configure the snapshot warehouse, modify the [pom.xml](https://github.com/tomoncle/mxnet-spring-samples/blob/master/pom.xml#L60) file, and cancel the warehouse configuration annotations. So all you need to do is configure the snapshot repository, just use the snapshot version ("[1.5.0-SNAPSHOT,)").

Next, run the compilation command：`$ mvn clean compile`

**Comment by git-mosis** [comment]
Thanks @tomoncle! For those following along, I created a fork as a reference for MAC OSX users and added additional images that work well for demo purposes. 

> `github.com/tomoncle/mxnet-spring-samples/pull/2#issue-284367329`
